misconfigurations:
  - id: AVD-AWS-0088
    statement: Bucket does not have encryption enabled
    paths:
      - src/main.tf
      - main.tf
  - id: AVD-AWS-0132
    statement: Bucket does not encrypt data with a customer managed key.
    paths:
      - src/main.tf
      - main.tf
  - id: AVD-AWS-0030
    statement: Image scanning is not enabled
    paths:
      - modules/lambda/main.tf
      - ../modules/lambda/main.tf
      - main.tf
  - id: AVD-AWS-0031
    statement: Repository tags are mutable.
    paths:
      - modules/lambda/main.tf
      - ../modules/lambda/main.tf
      - main.tf
  - id: AVD-AWS-0104
    statement: Security group rule allows unrestricted egress to any IP address.
    paths:
      - main.tf
      - src/main.tf
  - id: AVD-DS-0002
    statement: Specify at least 1 USER command in Dockerfile with non-root user as argument. We can ignore this based on the following AWS reference https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
    paths:
      - apps/Dockerfile
      - apps/api/Dockerfile
