misconfigurations:
  - id: AVD-AWS-0088
    statement: Bucket does not have encryption enabled
    paths:
      - src/main.tf
      - main.tf
  - id: AVD-AWS-0132
    statement: Bucket does not encrypt data with a customer managed key.
    paths:
      - src/main.tf
      - main.tf
  - id: AVD-AWS-0030
    statement: Image scanning is not enabled
    paths:
      - modules/lambda/main.tf
      - ../modules/lambda/main.tf
      - main.tf
  - id: AVD-AWS-0031
    statement: Repository tags are mutable.
    paths:
      - modules/lambda/main.tf
      - ../modules/lambda/main.tf
      - main.tf
