misconfigurations:
  - id: AVD-AWS-0088
    statement: Bucket does not have encryption enabled
    paths:
      - src/main.tf
      - main.tf
  - id: AVD-AWS-0132
    statement: Bucket does not encrypt data with a customer managed key.
    paths:
      - src/main.tf
      - main.tf
