name: Lambda Build and Push
description: Build Docker image for CI. Optionally push to ECR and update Lambda during CD.

inputs:
  deploy:
    description: "Whether to push the image to ECR and update Lambda (true/false)"
    required: false
    default: "false"
  working_directory:
    description: Path to the directory containing the Docker files
    required: true
  aws_region:
    description: AWS region to use
    required: true
  aws_role_arn:
    description: AWS IAM Role to assume via OIDC
    required: true
  lambda_name:
    description: Name of the Lambda to deploy
    required: true
  ecr_name:
    description: Name of the ECR repository to push the image to
    required: true
  build_args:
    description: "Optional Docker build args"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      if: ${{ inputs.deploy == 'false' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.working_directory }}
        file: ${{ inputs.working_directory }}/Dockerfile
        push: false
        tags: local-build:${{ github.sha }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha,scope=${{ inputs.ecr_name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.ecr_name }}

    - name: Configure AWS credentials
      if: ${{ inputs.deploy == 'true' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      if: ${{ inputs.deploy == 'true' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      if: ${{ inputs.deploy == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.working_directory }}
        file: ${{ inputs.working_directory }}/Dockerfile
        push: true
        provenance: false
        build-args: ${{ inputs.build_args }}
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_name }}:${{ github.sha }}
        cache-from: type=gha,scope=${{ inputs.ecr_name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.ecr_name }}

    - name: Update Lambda function
      if: ${{ inputs.deploy == 'true' }}
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_name }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws lambda update-function-code \
          --function-name "${{ inputs.lambda_name }}" \
          --image-uri "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
